services:
  app:
    build: .
    command: sh -c 'php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000'
    ports: [ 8000:8000 ]
    init: true
    environment:
      - APP_ENV=local
      - APP_KEY=12345678901234567890abcdefabcdea
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - APP_URL=http://localhost:8000/
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=pandora
      - DB_USERNAME=pandora
      - DB_PASSWORD=pandora

      - HODIS_API_URL=https://hodis.datasektionen.se
      - PORT=8000
      # SSO Configuration (OpenID Connect)
      # Required: OAuth2/OIDC client credentials from your SSO provider
      - SSO_CLIENT_ID=mathm-local
      - SSO_CLIENT_SECRET=vXgfGi4qD3hAvoPiDQsc3HneBJgZGQSl2TGGMUnScfg=
      # Required: SSO provider's issuer URL (OpenID Connect discovery endpoint)
      - SSO_ISSUER_URL=https://sso.datasektionen.se/op
      # Required: Callback URL where SSO will redirect after authentication
      # Must match the redirect URI registered with your SSO provider
      - SSO_REDIRECT_URI=http://localhost:8000/auth/callback
      # Optional: Where to redirect after SSO logout (defaults to APP_URL)
      - SSO_LOGOUT_REDIRECT_URI=http://localhost:8000/
      # Optional: SSL verification settings (recommended: true for production)
      - SSO_VERIFY_SSL=true
      # Optional: Request timeout in seconds (default: 30)
      - SSO_TIMEOUT=30
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: [vendor/]
        - action: rebuild
          path: composer.json
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=pandora
      - POSTGRES_USER=pandora
      - POSTGRES_DB=pandora
    healthcheck:
      test:
        - "CMD-SHELL"
        - "sh -c 'pg_isready -d pandora -U pandora'"
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s
  login:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    ports: [ 7002:7002 ]
    environment:
      - KTH_ID=mathm
