services:
  app:
    build:
      dockerfile: Dockerfile.dev
    ports: [ 8000:8000 ]
    init: true
    environment:
      - PORT=8000
      - APP_ENV=local
      - APP_KEY=12345678901234567890abcdefabcdef
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - APP_URL=http://localhost:8000/
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=pandora
      - DB_USERNAME=pandora
      - DB_PASSWORD=pandora
      - OIDC_PROVIDER=http://localhost:7003
      - OIDC_CLIENT_SECRET=client-secret
      - OIDC_CLIENT_ID=client-id
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: [vendor/]
        - action: rebuild
          path: composer.json
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=pandora
      - POSTGRES_USER=pandora
      - POSTGRES_DB=pandora
    healthcheck:
      test:
        - "CMD-SHELL"
        - "sh -c 'pg_isready -d pandora -U pandora'"
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s
  nyckeln:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    ports:
      - 7003:7003
      - 7004:7004
    configs:
      - source: nyckeln.yaml
        target: /config.yaml

configs:
  nyckeln.yaml:
    content: |
      clients:
        - id: client-id
          secret: client-secret
          redirect_uris:
            - http://localhost:8000/login

      users:
        - ug_kth_id: some-id
          kth_id: turetek
          email: turetek@kth.se
          first_name: Ture
          family_name: Teknolog

      hive:
        groups:
          - name: Systemansvarig
            id: d-sys
            domain: example.com
            members:
              - turetek
            permissions:
              - id: admin
